# Local Database Configuration mapping to exposed Docker port
spring.jpa.hibernate.ddl-auto=update

spring.datasource.url=jdbc:postgresql://localhost:5432/backend
spring.datasource.username=backend
spring.datasource.password=backend

# AI Service
ai.service.url=http://localhost:8080

# App base URL used in verification emails
app.base-url=http://localhost:5173

# Kafka
spring.kafka.bootstrap-servers=localhost:9092

email.send.enabled=false