# Local Database Configuration mapping to exposed Docker port
spring.jpa.hibernate.ddl-auto=update

spring.datasource.url=jdbc:postgresql://localhost:5432/backend
spring.datasource.username=backend
spring.datasource.password=backend

# AI Service
ai.service.url=http://localhost:8080

# Mail (SMTP)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=na.nashe.org@gmail.com
spring.mail.password=ooawcmaemewxfjqm

# App base URL used in verification emails
app.base-url=http://localhost:8080