spring.application.name=backend
spring.jpa.hibernate.ddl-auto=validate

# Docker Compose Database Configuration
spring.datasource.url=jdbc:postgresql://db:5432/backend
spring.datasource.username=backend
spring.datasource.password=backend

# AI Service
ai.service.url=http://ai-service:8080

# JWT RSA keys
jwt.private-key-path=classpath:certs/private.pem
jwt.public-key-path=classpath:certs/public.pem

# JWT token expiration in seconds
access.token.expiration.time=3600
